import {createRequire} from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.ECOMMERCE_URL || 'http://127.0.0.1:8012';
const browser=await chromium.launch({channel:'msedge',headless:true});
const report={status:'running',browser:'Microsoft Edge via Playwright',real_api:[],frontend_fault_injection:[]};
fs.mkdirSync('reports/private',{recursive:true});
try {
 const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();
 await page.goto(base,{waitUntil:'networkidle'});
 await page.getByText('离线演示 · 本地规则与事实模板',{exact:true}).waitFor();
 const input=page.getByLabel('您的问题');
 await input.fill(process.env.ECOMMERCE_DEMO_QUESTION || '随行水杯价格');
 const answerPromise=page.waitForResponse(r=>r.url()===base+'/api/chat' && r.request().method()==='POST');
 await page.getByRole('button',{name:'查询 ↗'}).click();
 const answer=await answerPromise;const value=await answer.json();assert.equal(answer.status(),200);assert.equal(value.status,'ok');assert.ok(value.evidence.length>0);
 await page.getByText(value.message,{exact:true}).waitFor();
 await page.screenshot({path:'reports/private/chat-real-desktop.png',fullPage:true});report.real_api.push('actual evidence-backed answer visible');
 await input.fill('<img src=x onerror="window.__xss=1">');
 const xssReply=page.waitForResponse(r=>r.url()===base+'/api/chat');await input.press('Enter');await xssReply;
 assert.equal(await page.evaluate(()=>window.__xss),undefined);assert.equal(await page.locator('#messages img').count(),0);report.real_api.push('user XSS text remains text');
 await page.waitForFunction(()=>!document.querySelector('#send').disabled);
 let requests=0;
 await page.route('**/api/chat',async route=>{requests++;await new Promise(resolve=>setTimeout(resolve,600));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'explicit browser mock only',status:'ok',trace_id:'e2e-mock',evidence:[]})});});
 await input.fill('中文输入法测试');await input.dispatchEvent('compositionstart');await input.press('Enter');assert.equal(requests,0);await input.dispatchEvent('compositionend');
 await input.press('Enter');await input.press('Enter');await input.press('Enter');await page.getByText('explicit browser mock only',{exact:true}).waitFor();assert.equal(requests,1);report.frontend_fault_injection.push('IME and repeated Enter share one request lock');
 await page.waitForFunction(()=>!document.querySelector('#send').disabled);await page.unroute('**/api/chat');
 await page.route('**/api/chat',route=>route.fulfill({status:503,contentType:'application/json',body:'{"message":"failure"}'}));
 await input.fill('服务故障');await input.press('Enter');await page.getByText('服务返回 HTTP 503，请检查服务后重试。',{exact:true}).first().waitFor();report.frontend_fault_injection.push('HTTP non-OK visible');
 await page.unroute('**/api/chat');await page.waitForFunction(()=>!document.querySelector('#send').disabled);
 await page.route('**/api/chat',route=>route.abort('internetdisconnected'));
 await input.fill('网络中断');await input.press('Enter');await page.waitForFunction(()=>!document.querySelector('#send').disabled);assert.ok((await page.locator('#status').innerText()).includes('Failed'));report.frontend_fault_injection.push('network failure unlocks form');
 await page.unroute('**/api/chat');
 await page.route('**/api/chat',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'<script>window.__xss=2</script>',status:'ok'})}));
 await input.fill('模型输出安全测试');await input.press('Enter');await page.getByText('<script>window.__xss=2</script>',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__xss),undefined);report.frontend_fault_injection.push('answer XSS text remains text');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'reports/private/chat-mobile-regression.png',fullPage:true});
 await page.unroute('**/api/chat');await page.waitForFunction(()=>!document.querySelector('#send').disabled);
 await page.clock.install();
 let held;
 await page.route('**/api/chat',route=>{held=route;});
 await input.fill('超时测试');await input.press('Enter');await page.clock.runFor(46000);
 await page.getByText('请求已取消或超时，可重新发送。',{exact:true}).first().waitFor();
 assert.equal(await page.getByRole('button',{name:'查询 ↗'}).isEnabled(),true);
 if(held)await held.abort().catch(()=>{});
 report.frontend_fault_injection.push('45-second timeout simulated with browser clock; form unlocks');
 await input.fill('主动取消测试');await input.press('Enter');await page.getByRole('button',{name:'取消',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#send').disabled);if(held)await held.abort().catch(()=>{});
 report.frontend_fault_injection.push('explicit cancel unlocks form');
 report.status='passed';
} catch(error) {report.status='failed';report.error=String(error);throw error;}
finally {fs.writeFileSync('reports/private/browser-e2e.json',JSON.stringify(report,null,2));await browser.close();}
console.log(JSON.stringify(report));
